### ISSUE TITLE
# A QUESTION FROM THE DEPLOYED THAT SEEMS TO NOT BE WORKING.

### ISSUE THREAD

**Issue by Kahono0** [CreamyMilk/DarajaSTK#7]
Previously when I visited the deployment it used to send an stk push to my phone requesting me to send 1 bob to you :) 
My question is , does mpesa api support customer to customer transactions. If yes , how .

**Comment by CreamyMilk** [comment]
I'll update it 👍.

**Comment by CreamyMilk** [comment]
> Previously when I visited the deployment it used to send an stk push to my phone requesting me to send 1 bob to you :)
> My question is , does mpesa api support customer to customer transactions. If yes , how .

Customer to customer payments are not yet supported via Daraja for now.
